project:
  type: website
  output-dir: docs

website:
  title: "Matteo Aldovardi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Notes.qmd
      - About.qmd
format:
  html:
    theme: lux
    css: styles.css
    fontcolor: "#D5A93D"
    toc: true



