---
title: "About"
format: html
editor: visual
---

Hey there, I'm Matteo Aldovardi, and I've got a passion for math. I studied math at the University of Pisa.

I graduated on October 28th with a thesis in Harmonic Analysis. You can actually find it in the University's archive if you're curious:

[**https://etd.adm.unipi.it/theses/available/etd-10012022-110009/**](https://etd.adm.unipi.it/theses/available/etd-10012022-110009/)

I also teamed up with my thesis advisor to write an article based on the work I did during my thesis. It's about a refined version of the Hardy Fractional Inequality. If that piques your interest, you can read it here:

[**https://link.springer.com/article/10.1007/s40574-023-00359-7#article-info**](https://link.springer.com/article/10.1007/s40574-023-00359-7#article-info)

After graduating, I decided to continue my journey in mathematics and also explored the world of machine learning. I took Andrew Ng's course on Coursera and delved into introductory courses on Python and R.

If you're interested, here's the link to Andrew Ng's course: [**https://coursera.org/share/1ea8e91ad87b22ce2b3272de89f7cc30**](https://coursera.org/share/1ea8e91ad87b22ce2b3272de89f7cc30)

As of October 2023, I'm currently enrolled in Jeremy Howard's fastai course. As part of my coursework, I worked on a neural net project. You can check it out here:

[**https://huggingface.co/spaces/MatteoAld/Muri**](https://huggingface.co/spaces/MatteoAld/Muri)
